#pragma config(Sensor, port2,  rusw,           sensorVexIQ_LED)
#pragma config(Sensor, port3,  lusw,           sensorVexIQ_LED)
#pragma config(Sensor, port4,  rdsw,           sensorVexIQ_Touch)
#pragma config(Sensor, port11, ldsw,           sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          rm,            tmotorNone, openLoop)
#pragma config(Motor,  motor6,          lm,            tmotorNone, openLoop)
#pragma config(Motor,  motor12,         pm,            tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Ask the user to move the bot to the home position (left upper corner)
void promptHome(void)
{
	int spd = 10;
	int lms = 0;
	int rms = 0;
	eraseDisplay();
	displayString(1,"Please move the Bot");
	displayString(2,"to the bottom");
	displayString(3,"lefthand corner");
	displayString(4,"Press ^ when done");

	while(!nLCDButtons) { // Loop until button pressed
		lms = 0;
		rms = 0;
		if(getTouchLEDValue(lusw))
			lms = spd;
		if(getTouchLEDValue(rusw))
			rms = spd;
		if(getBumperValue(ldsw))
			lms = -spd;
		if(getBumperValue(rdsw))
			rms = -spd;
		setMotorSpeed(lm, lms);
		setMotorSpeed(rm, rms);
    sleep(5);
	}
	resetMotorEncoder(lm);
	resetMotorEncoder(rm);
	eraseDisplay();
	displayString(1,"now to the upper");
	displayString(2,"righthand corner");
	displayString(4,"Press ^ when done");
	while(nLCDButtons)
	  sleep(5);
	while(!nLCDButtons) { // Loop until button pressed
		lms = 0;
		rms = 0;
		if(getTouchLEDValue(lusw))
			lms = spd;
		if(getTouchLEDValue(rusw))
			rms = spd;
		if(getBumperValue(ldsw))
			lms = -spd;
		if(getBumperValue(rdsw))
			rms = -spd;
		setMotorSpeed(lm, lms);
		setMotorSpeed(rm, rms);
    sleep(5);
  	displayString(3,"                        ");
  	displayString(3,"l %d, r %d",getMotorEncoder(lm),getMotorEncoder(rm));
	}
}

void setPen(int on)
{
	if(on) {
		setServoTarget(pm,0);
		setTouchLEDColor(lusw,colorGreen);
		setTouchLEDColor(rusw,colorGreen);
	}
	else {
		setServoTarget(pm,-90);
		setTouchLEDColor(lusw,colorRedViolet);
		setTouchLEDColor(rusw,colorRedViolet);
	}

}

task main()
{
	int uprt_lm, uprt_rm;
	setMotorReversed(rm,true);
	setMotorReversed(lm,false);
	promptHome();
	uprt_lm = getMotorEncoder(lm);
	uprt_rm = getMotorEncoder(rm);
	while(1) {
		setPen(1);
		sleep(500);
		setPen(0);
		sleep(500);
	}
}
